from util import e, p


def equations_s(oo, ov, vo, vv, oovo, oovv, ovvo, ovvv, t1):
    hE = scalar = 0
    hE += e("ab,ib->ia", vv, t1)  # d1_ov
    hE -= e("ij,ia->ja", oo, t1)  # d3_ov
    hE += e("ai->ia", vo)  # d4_ov
    hE -= e("ib,ia,jb->ja", ov, t1, t1)  # d7_ov
    scalar += e("ia,ia", ov, t1)  # s9
    hE += e("icab,ia,jb->jc", ovvv, t1, t1)  # d12_ov
    hE += e("ibaj,ia->jb", ovvo, t1)  # d15_ov
    hE += e("kibc,ia,jb,kc->ja", oovv, t1, t1, t1)  # d19_ov
    scalar += 1./2 * e("ijab,ia,jb", oovv, t1, t1)  # s24
    hE += e("ikbj,ia,kb->ja", oovo, t1, t1)  # d27_ov
    return hE, scalar


def equations_sd(oo, ov, vo, vv, oooo, oovo, oovv, ovoo, ovvo, ovvv, vvoo, vvvo, vvvv, t1, t2):
    hE = hhEE = scalar = 0
    hE += e("ab,ib->ia", vv, t1)  # d1_ov
    hhEE += p("..ab", e("ba,jiac->ijcb", vv, t2))  # d2_oovv
    hE -= e("ij,ia->ja", oo, t1)  # d4_ov
    hhEE -= p("ab..", e("kj,kiab->ijba", oo, t2))  # d5_oovv
    hE += e("ai->ia", vo)  # d6_ov
    hE -= e("jb,ib,ja->ia", ov, t1, t1)  # d9_ov
    hhEE -= p("ab..", e("ia,ka,ijbc->jkcb", ov, t1, t2))  # d10_oovv
    hhEE -= p("..ab", e("ia,ib,kjac->jkcb", ov, t1, t2))  # d12_oovv
    scalar += e("ia,ia", ov, t1)  # s13
    hE += e("ia,ijab->jb", ov, t2)  # d16_ov
    hhEE += 1./2 * p("ab..", e("cbda,ia,jd->jicb", vvvv, t1, t1))  # d19_oovv
    hhEE += 1./2 * e("dcba,ijba->ijdc", vvvv, t2)  # d20_oovv
    hhEE += p("ab..", e("cbaj,ia->ijcb", vvvo, t1))  # d22_oovv
    hhEE += e("baij->ijba", vvoo)  # d23_oovv
    hhEE -= 1./2 * p("ab..", p("..ab", e("kbcd,ic,ka,jd->ijab", ovvv, t1, t1, t1)))  # d27_oovv
    hE -= e("icba,jb,ia->jc", ovvv, t1, t1)  # d29_ov
    hhEE -= p("ab..", p("..ab", e("kacd,ic,kjdb->ijab", ovvv, t1, t2)))  # d30_oovv
    hhEE -= 1./2 * p("..ab", e("kbdc,ka,jidc->ijba", ovvv, t1, t2))  # d32_oovv
    hhEE += p("..ab", e("kcdb,kd,ijba->ijca", ovvv, t1, t2))  # d34_oovv
    hE += 1./2 * e("icba,ijba->jc", ovvv, t2)  # d38_ov
    hhEE -= p("ab..", p("..ab", e("jabi,kb,jc->kica", ovvo, t1, t1)))  # d41_oovv
    hE += e("ibaj,ia->jb", ovvo, t1)  # d43_ov
    hhEE += p("ab..", p("..ab", e("kbcj,kica->ijab", ovvo, t2)))  # d44_oovv
    hhEE -= p("..ab", e("kaji,kb->ijab", ovoo, t1))  # d46_oovv
    hhEE += 1./4 * p("ab..", p("..ab", e("lkda,ia,jd,kb,lc->jicb", oovv, t1, t1, t1, t1)))  # d51_oovv
    hhEE += 1./4 * p("ab..", e("ijab,ka,lb,ijdc->kldc", oovv, t1, t1, t2))  # d52_oovv
    hE -= e("jibc,ia,jb,kc->ka", oovv, t1, t1, t1)  # d55_ov
    hhEE -= p("ab..", p("..ab", e("klcd,lb,jd,kica->ijab", oovv, t1, t1, t2)))  # d56_oovv
    hhEE += p("ab..", e("liab,ia,jb,lkdc->jkdc", oovv, t1, t1, t2))  # d58_oovv
    hE -= 1./2 * e("jkba,ia,jkbc->ic", oovv, t1, t2)  # d62_ov
    hhEE += 1./4 * p("..ab", e("ijdc,ia,jb,kldc->klab", oovv, t1, t1, t2))  # d65_oovv
    hhEE -= p("..ab", e("kldc,kd,lb,ijca->ijba", oovv, t1, t1, t2))  # d67_oovv
    hE -= 1./2 * e("jkcb,ka,jicb->ia", oovv, t1, t2)  # d71_ov
    scalar += 1./2 * e("ijab,jb,ia", oovv, t1, t1)  # s73
    hE += e("kjcb,jb,kica->ia", oovv, t1, t2)  # d76_ov
    hhEE -= 1./2 * p("..ab", e("ijbd,ijba,lkdc->klca", oovv, t2, t2))  # d78_oovv
    hhEE += 1./4 * e("ijdc,ijba,lkdc->klab", oovv, t2, t2)  # d80_oovv
    hhEE += 1./2 * p("ab..", e("ljba,jiba,lkdc->ikdc", oovv, t2, t2))  # d82_oovv
    hhEE += 1./2 * p("ab..", p("..ab", e("ljdb,jiba,lkdc->kica", oovv, t2, t2)))  # d84_oovv
    scalar += 1./4 * e("ijba,ijba", oovv, t2)  # s88
    hhEE += 1./2 * p("ab..", p("..ab", e("licj,ia,lb,kc->kjba", oovo, t1, t1, t1)))  # d92_oovv
    hhEE += 1./2 * p("ab..", e("ijck,lc,ijba->klab", oovo, t1, t2))  # d93_oovv
    hE += e("kiaj,ia,kb->jb", oovo, t1, t1)  # d96_ov
    hhEE -= p("ab..", p("..ab", e("jkai,kb,jlac->ilbc", oovo, t1, t2)))  # d97_oovv
    hhEE += p("ab..", e("jlck,lc,jiba->ikab", oovo, t1, t2))  # d99_oovv
    hE -= 1./2 * e("ijak,ijab->kb", oovo, t2)  # d103_ov
    hhEE += 1./2 * p("..ab", e("ilkj,ia,lb->jkba", oooo, t1, t1))  # d106_oovv
    hhEE += 1./2 * e("ijlk,ijba->klab", oooo, t2)  # d107_oovv
    return hE, hhEE, scalar


def equations_sdt(oo, ov, vo, vv, oooo, oovo, oovv, ovoo, ovvo, ovvv, vvoo, vvvo, vvvv, t1, t2, t3):
    hE = hhEE = hhhEEE = scalar = 0
    hE += e("ba,ia->ib", vv, t1)  # d1_ov
    hhEE += p("..ab", e("bc,jica->ijab", vv, t2))  # d2_oovv
    hhhEEE += p("...aba", e("cd,kjidba->jkibca", vv, t3))  # d3_ooovvv
    hE -= e("ij,ia->ja", oo, t1)  # d5_ov
    hhEE -= p("ab..", e("jk,jiba->ikab", oo, t2))  # d6_oovv
    hhhEEE -= p("aba...", e("ij,ilkbca->ljkcba", oo, t3))  # d7_ooovvv
    hE += e("ai->ia", vo)  # d8_ov
    hE -= e("ia,ja,ib->jb", ov, t1, t1)  # d11_ov
    hhEE -= p("ab..", e("ia,ka,ijbc->jkcb", ov, t1, t2))  # d12_oovv
    hhhEEE -= p("abb...", e("la,ia,ljkdbc->ikjdcb", ov, t1, t3))  # d13_ooovvv
    hhEE -= p("..ab", e("ic,ia,kjcb->jkba", ov, t1, t2))  # d15_oovv
    hhhEEE -= p("...aab", e("ia,ib,jlkacd->kljdcb", ov, t1, t3))  # d16_ooovvv
    scalar += e("ia,ia", ov, t1)  # s17
    hhhEEE -= p("abb...", p("...aab", e("ld,liab,kjdc->ikjbac", ov, t2, t2)))  # d19_ooovvv
    hE += e("jb,jiba->ia", ov, t2)  # d21_ov
    hhEE += e("ia,ikjacb->kjcb", ov, t3)  # d24_oovv
    hhEE += 1./2 * p("ab..", e("bacd,ic,jd->ijba", vvvv, t1, t1))  # d27_oovv
    hhhEEE += p("aba...", p("...aab", e("dcae,ke,ijab->ikjdcb", vvvv, t1, t2)))  # d28_ooovvv
    hhEE += 1./2 * e("dcba,ijba->ijdc", vvvv, t2)  # d30_oovv
    hhhEEE += 1./2 * p("...abb", e("badc,jkidce->ikjeab", vvvv, t3))  # d31_ooovvv
    hhEE += p("ab..", e("baci,jc->ijab", vvvo, t1))  # d33_oovv
    hhhEEE += p("aba...", p("...abb", e("cbai,jkad->kijdbc", vvvo, t2)))  # d34_ooovvv
    hhEE += e("baij->ijba", vvoo)  # d35_oovv
    hhEE -= 1./2 * p("ab..", p("..ab", e("iabc,id,jc,kb->jkad", ovvv, t1, t1, t1)))  # d39_oovv
    hhhEEE -= 1./2 * p("abc...", p("...aab", e("ibac,kc,la,ijed->jlkdeb", ovvv, t1, t1, t2)))  # d40_ooovvv
    hhhEEE -= p("abb...", p("...abc", e("ibde,ia,je,kldc->jlkbca", ovvv, t1, t1, t2)))  # d42_ooovvv
    hE -= e("jabc,ib,jc->ia", ovvv, t1, t1)  # d43_ov
    hhEE += p("ab..", p("..ab", e("iabc,kc,ijbd->jkda", ovvv, t1, t2)))  # d46_oovv
    hhhEEE += p("aba...", p("...aba", e("idae,le,ikjacb->jlkbdc", ovvv, t1, t3)))  # d47_ooovvv
    hhEE -= 1./2 * p("..ab", e("icba,id,jkba->jkdc", ovvv, t1, t2))  # d50_oovv
    hhhEEE -= 1./2 * p("...abc", e("icba,id,kjlbae->kljdec", ovvv, t1, t3))  # d51_ooovvv
    hhEE += p("..ab", e("ibac,ia,kjcd->jkdb", ovvv, t1, t2))  # d53_oovv
    hhhEEE -= p("...abb", e("idea,ia,kljecb->kljdcb", ovvv, t1, t3))  # d54_ooovvv
    hhhEEE -= p("aab...", p("...abc", e("idca,ijab,klce->kljdeb", ovvv, t2, t2)))  # d56_ooovvv
    hhhEEE -= 1./2 * p("aba...", p("...aab", e("laed,jied,lkcb->jkicba", ovvv, t2, t2)))  # d58_ooovvv
    hE += 1./2 * e("jacb,jicb->ia", ovvv, t2)  # d61_ov
    hhEE += 1./2 * p("..ab", e("kbdc,kijdca->ijba", ovvv, t3))  # d65_oovv
    hhEE -= p("ab..", p("..ab", e("ibcj,ia,kc->jkba", ovvo, t1, t1)))  # d68_oovv
    hhhEEE -= p("abc...", p("...aba", e("lbaj,ia,lkdc->ijkdbc", ovvo, t1, t2)))  # d69_ooovvv
    hhhEEE -= p("aba...", p("...abc", e("lcbk,ld,ijba->ikjdca", ovvo, t1, t2)))  # d71_ooovvv
    hE += e("jabi,jb->ia", ovvo, t1)  # d72_ov
    hhEE += p("ab..", p("..ab", e("kaci,kjcb->ijab", ovvo, t2)))  # d75_oovv
    hhhEEE += p("aab...", p("...aab", e("ibaj,ilkadc->lkjdcb", ovvo, t3)))  # d76_ooovvv
    hhEE -= p("..ab", e("ibjk,ia->kjba", ovoo, t1))  # d78_oovv
    hhhEEE -= p("aba...", p("...abb", e("ickl,ijba->ljkcab", ovoo, t2)))  # d79_ooovvv
    hhEE += 1./4 * p("ab..", p("..ab", e("ijcd,ia,jb,kd,lc->lkab", oovv, t1, t1, t1, t1)))  # d84_oovv
    hhhEEE += 1./2 * p("abc...", p("...aab", e("iked,ia,le,md,kjcb->mjlcba", oovv, t1, t1, t1, t2)))  # d85_ooovvv
    hhEE += 1./4 * p("ab..", e("ijcd,kc,ld,ijba->lkab", oovv, t1, t1, t2))  # d87_oovv
    hhhEEE += 1./4 * p("abc...", e("ijab,ka,mb,ijledc->kmledc", oovv, t1, t1, t3))  # d88_ooovvv
    hhhEEE += 1./2 * p("aab...", p("...abc", e("jiba,jc,ka,id,mlbe->lmkecd", oovv, t1, t1, t1, t2)))  # d91_ooovvv
    hE += e("kiac,ia,jc,kb->jb", oovv, t1, t1, t1)  # d92_ov
    hhEE -= p("ab..", p("..ab", e("ijba,jc,la,ikbd->kldc", oovv, t1, t1, t2)))  # d95_oovv
    hhhEEE += p("abb...", p("...abb", e("jkca,ia,jb,kmlced->imlbed", oovv, t1, t1, t3)))  # d96_ooovvv
    hhEE += p("ab..", e("lkcd,kc,id,ljab->jiba", oovv, t1, t1, t2))  # d98_oovv
    hhhEEE += p("abb...", e("kiab,ia,jb,kmledc->jmledc", oovv, t1, t1, t3))  # d99_ooovvv
    hhhEEE += 1./2 * p("aba...", p("...abb", e("ijdc,mc,ijba,klde->lmkeab", oovv, t1, t2, t2)))  # d101_ooovvv
    hhhEEE -= p("abc...", p("...aab", e("ijab,la,jkbc,imed->lmkedc", oovv, t1, t2, t2)))  # d103_ooovvv
    hE -= 1./2 * e("jkca,ia,jkcb->ib", oovv, t1, t2)  # d106_ov
    hhEE -= 1./2 * p("ab..", e("ijba,ka,ijlbdc->kldc", oovv, t1, t3))  # d110_oovv
    hhEE += 1./4 * p("..ab", e("ijcb,ia,jd,klcb->lkda", oovv, t1, t1, t2))  # d114_oovv
    hhhEEE += 1./4 * p("...abc", e("imed,ia,mc,jkledb->kljcba", oovv, t1, t1, t3))  # d115_ooovvv
    hhEE -= p("..ab", e("licd,ia,lc,kjdb->jkba", oovv, t1, t1, t2))  # d117_oovv
    hhhEEE -= p("...abb", e("lmde,ld,mc,jikeab->jkicba", oovv, t1, t1, t3))  # d118_ooovvv
    hhhEEE += p("abb...", p("...abc", e("mide,ia,jkdb,mlec->lkjcba", oovv, t1, t2, t2)))  # d120_ooovvv
    hhhEEE += 1./2 * p("abb...", p("...aab", e("mied,ia,mlbc,kjed->lkjcba", oovv, t1, t2, t2)))  # d122_ooovvv
    hE -= 1./2 * e("ikba,kc,ijba->jc", oovv, t1, t2)  # d125_ov
    hhEE -= 1./2 * p("..ab", e("ijba,jd,iklbac->kldc", oovv, t1, t3))  # d129_oovv
    scalar += 1./2 * e("jiba,ia,jb", oovv, t1, t1)  # s131
    hhhEEE -= p("aba...", p("...aab", e("mkac,kc,ijab,mled->iljedb", oovv, t1, t2, t2)))  # d133_ooovvv
    hE += e("kica,ia,kjcb->jb", oovv, t1, t2)  # d135_ov
    hhEE += e("lkdc,kc,ljidab->ijba", oovv, t1, t3)  # d138_oovv
    hhEE += 1./2 * p("..ab", e("ijab,lkac,ijbd->klcd", oovv, t2, t2))  # d143_oovv
    hhhEEE += 1./2 * p("aba...", p("...aab", e("lmae,ijab,lmkedc->ikjdcb", oovv, t2, t3)))  # d144_ooovvv
    hhEE += 1./4 * e("klba,ijba,kldc->ijdc", oovv, t2, t2)  # d147_oovv
    hhhEEE += 1./4 * p("aab...", e("lmed,ijed,lmkcba->ijkcba", oovv, t2, t3))  # d148_ooovvv
    hhEE += 1./2 * p("ab..", e("ildc,ijba,lkdc->jkab", oovv, t2, t2))  # d151_oovv
    hhhEEE += 1./2 * p("aba...", p("...abb", e("imed,ijba,mkledc->ljkcab", oovv, t2, t3)))  # d152_ooovvv
    hhEE += 1./2 * p("ab..", p("..ab", e("lkdc,kica,ljdb->jiba", oovv, t2, t2)))  # d154_oovv
    hhhEEE += p("aba...", p("...aba", e("mkec,mled,kjicba->jlibda", oovv, t2, t3)))  # d155_ooovvv
    hhhEEE -= 1./2 * p("abb...", e("imba,ijba,mlkedc->jlkedc", oovv, t2, t3))  # d157_ooovvv
    hhhEEE += 1./4 * p("...abb", e("ijed,ijba,kmledc->lmkcab", oovv, t2, t3))  # d159_ooovvv
    hhhEEE -= 1./2 * p("...aab", e("ijbe,ijba,kmlecd->lmkdca", oovv, t2, t3))  # d161_ooovvv
    scalar += 1./4 * e("ijba,ijba", oovv, t2)  # s162
    hE += 1./4 * e("ijba,ijkbac->kc", oovv, t3)  # d170_ov
    hhEE += 1./2 * p("ab..", p("..ab", e("ikbj,ia,lb,kc->jlca", oovo, t1, t1, t1)))  # d174_oovv
    hhhEEE += p("abc...", p("...abb", e("klaj,ia,kd,lmcb->ijmdcb", oovo, t1, t1, t2)))  # d175_ooovvv
    hhEE += 1./2 * p("ab..", e("klci,jc,klab->ijba", oovo, t1, t2))  # d177_oovv
    hhhEEE += 1./2 * p("abc...", e("ijdm,ld,ijkcba->kmlabc", oovo, t1, t3))  # d178_ooovvv
    hhhEEE += 1./2 * p("aab...", p("...abc", e("mldi,lb,mc,kjda->jkiacb", oovo, t1, t1, t2)))  # d181_ooovvv
    hE -= e("jibk,ia,jb->ka", oovo, t1, t1)  # d182_ov
    hhEE += p("ab..", p("..ab", e("ilck,ia,ljcb->jkba", oovo, t1, t2)))  # d185_oovv
    hhhEEE += p("abb...", p("...abb", e("ikaj,id,klmabc->jmldcb", oovo, t1, t3)))  # d186_ooovvv
    hhEE += p("ab..", e("jial,ia,jkcb->klbc", oovo, t1, t2))  # d188_oovv
    hhhEEE -= p("abb...", e("jiak,ja,ilmdbc->kmldcb", oovo, t1, t3))  # d189_ooovvv
    hhhEEE += 1./2 * p("aba...", p("...aab", e("lmdk,jida,lmcb->jkicba", oovo, t2, t2)))  # d191_ooovvv
    hhhEEE += p("abc...", p("...abb", e("imdl,ijba,mkdc->kjlcab", oovo, t2, t2)))  # d193_ooovvv
    hE -= 1./2 * e("ijak,ijab->kb", oovo, t2)  # d196_ov
    hhEE -= 1./2 * p("ab..", e("klci,kljcba->ijba", oovo, t3))  # d200_oovv
    hhEE += 1./2 * p("..ab", e("ilkj,ia,lb->jkba", oooo, t1, t1))  # d203_oovv
    hhhEEE += p("aab...", p("...abb", e("ijkl,ic,jmba->klmcba", oooo, t1, t2)))  # d204_ooovvv
    hhEE += 1./2 * e("klij,klba->ijba", oooo, t2)  # d206_oovv
    hhhEEE += 1./2 * p("aab...", e("ijkl,ijmcba->klmcba", oooo, t3))  # d207_ooovvv
    return hE, hhEE, hhhEEE, scalar
