from util import e, p


def equations_s(oo, ov, vo, vv, oovo, oovv, ovvo, ovvv, t1):
    hE = scalar = 0
    hE += e("ba,ia->ib", vv, t1)  # d1_ov
    hE += e("ai->ia", vo)  # d2_ov
    hE -= e("ib,ia,jb->ja", ov, t1, t1)  # d5_ov
    scalar += e("ia,ia", ov, t1)  # s7
    hE -= e("ji,ja->ia", oo, t1)  # d9_ov
    hE -= e("icba,ia,jb->jc", ovvv, t1, t1)  # d12_ov
    hE += e("ibaj,ia->jb", ovvo, t1)  # d15_ov
    hE += e("ijba,ic,jb,ka->kc", oovv, t1, t1, t1)  # d19_ov
    scalar += 1./2 * e("ijab,ia,jb", oovv, t1, t1)  # s24
    hE += e("jiak,ia,jb->kb", oovo, t1, t1)  # d27_ov
    return hE, scalar


def equations_sd(oo, ov, vo, vv, oooo, oovo, oovv, ovoo, ovvo, ovvv, vvoo, vvvo, vvvv, t1, t2):
    hE = hhEE = scalar = 0
    hE += e("ab,ib->ia", vv, t1)  # d1_ov
    hhEE += p("..ab", e("ab,ijbc->ijac", vv, t2))  # d2_oovv
    hE += e("ai->ia", vo)  # d3_ov
    hE -= e("ib,ia,jb->ja", ov, t1, t1)  # d6_ov
    scalar += e("ia,ia", ov, t1)  # s8
    hhEE -= p("..ab", e("kb,kc,ijba->ijca", ov, t1, t2))  # d10_oovv
    hhEE -= p("ab..", e("ka,ia,kjcb->ijcb", ov, t1, t2))  # d12_oovv
    hE += e("jb,jiba->ia", ov, t2)  # d13_ov
    hE -= e("ji,ja->ia", oo, t1)  # d15_ov
    hhEE -= p("ab..", e("ji,jkba->ikba", oo, t2))  # d16_oovv
    hhEE += 1./2 * p("ab..", e("bacd,id,jc->ijab", vvvv, t1, t1))  # d19_oovv
    hhEE += 1./2 * e("badc,ijdc->ijba", vvvv, t2)  # d20_oovv
    hhEE += p("ab..", e("baci,jc->ijab", vvvo, t1))  # d22_oovv
    hhEE += e("baij->ijba", vvoo)  # d23_oovv
    hhEE -= 1./2 * p("ab..", p("..ab", e("ibcd,ia,jc,kd->jkab", ovvv, t1, t1, t1)))  # d27_oovv
    hE += e("jcba,ia,jb->ic", ovvv, t1, t1)  # d29_ov
    hhEE += p("..ab", e("kdcb,kc,ijba->ijda", ovvv, t1, t2))  # d33_oovv
    hhEE -= 1./2 * p("..ab", e("idcb,ia,jkcb->jkad", ovvv, t1, t2))  # d35_oovv
    hhEE -= p("ab..", p("..ab", e("iabc,kb,ijcd->jkda", ovvv, t1, t2)))  # d37_oovv
    hE += 1./2 * e("iacb,ijcb->ja", ovvv, t2)  # d38_ov
    hhEE -= p("ab..", p("..ab", e("kbaj,ia,kc->ijcb", ovvo, t1, t1)))  # d41_oovv
    hE += e("jabi,jb->ia", ovvo, t1)  # d43_ov
    hhEE += p("ab..", p("..ab", e("jabi,jkbc->ikac", ovvo, t2)))  # d44_oovv
    hhEE -= p("..ab", e("ibjk,ia->jkab", ovoo, t1))  # d46_oovv
    hhEE += 1./4 * p("ab..", p("..ab", e("kjac,ia,jb,lc,kd->ildb", oovv, t1, t1, t1, t1)))  # d51_oovv
    hE += e("kjac,ia,jb,kc->ib", oovv, t1, t1, t1)  # d54_ov
    scalar += 1./2 * e("ijab,jb,ia", oovv, t1, t1)  # s60
    hhEE -= p("..ab", e("ijab,ia,jc,klbd->klcd", oovv, t1, t1, t2))  # d63_oovv
    hhEE += 1./2 * p("..ab", e("ijcb,ijba,klcd->klad", oovv, t2, t2))  # d65_oovv
    hhEE += 1./4 * p("..ab", e("licb,ia,ld,jkcb->jkda", oovv, t1, t1, t2))  # d68_oovv
    hhEE += 1./4 * e("ijdc,ijba,kldc->klba", oovv, t2, t2)  # d69_oovv
    hhEE -= p("ab..", e("jkab,ia,kb,jldc->ildc", oovv, t1, t1, t2))  # d72_oovv
    hhEE -= 1./2 * p("ab..", e("jkba,jiba,kldc->ildc", oovv, t2, t2))  # d74_oovv
    hhEE -= p("ab..", p("..ab", e("kjcb,lc,kd,jiba->ilad", oovv, t1, t1, t2)))  # d77_oovv
    hE += e("ijab,ia,jkbc->kc", oovv, t1, t2)  # d79_ov
    hhEE += 1./2 * p("ab..", p("..ab", e("jiba,jkbc,ilad->klcd", oovv, t2, t2)))  # d80_oovv
    hE -= 1./2 * e("ijba,jc,ikba->kc", oovv, t1, t2)  # d82_ov
    hhEE += 1./4 * p("ab..", e("ijab,kb,la,ijdc->klcd", oovv, t1, t1, t2))  # d85_oovv
    hE += 1./2 * e("jkab,ia,jkbc->ic", oovv, t1, t2)  # d87_ov
    scalar += 1./4 * e("ijba,ijba", oovv, t2)  # s88
    hhEE += 1./2 * p("ab..", p("..ab", e("kibj,ia,lb,kc->jlac", oovo, t1, t1, t1)))  # d92_oovv
    hE += e("ikbj,ia,kb->ja", oovo, t1, t1)  # d95_ov
    hhEE += p("ab..", e("jlck,lc,jiba->ikab", oovo, t1, t2))  # d98_oovv
    hhEE -= p("ab..", p("..ab", e("kjai,jc,klab->ilcb", oovo, t1, t2)))  # d100_oovv
    hhEE += 1./2 * p("ab..", e("klaj,ia,klcb->ijcb", oovo, t1, t2))  # d102_oovv
    hE -= 1./2 * e("jkai,jkab->ib", oovo, t2)  # d103_ov
    hhEE += 1./2 * p("..ab", e("klij,la,kb->ijba", oooo, t1, t1))  # d106_oovv
    hhEE += 1./2 * e("ijkl,ijba->klba", oooo, t2)  # d107_oovv
    return hE, hhEE, scalar


def equations_sdt(oo, ov, vo, vv, oooo, oovo, oovv, ovoo, ovvo, ovvv, vvoo, vvvo, vvvv, t1, t2, t3):
    hE = hhEE = hhhEEE = scalar = 0
    hE += e("ab,ib->ia", vv, t1)  # d1_ov
    hhEE += p("..ab", e("cb,ijba->ijca", vv, t2))  # d2_oovv
    hhhEEE += p("...aba", e("dc,jkicba->ijkadb", vv, t3))  # d3_ooovvv
    hE += e("ai->ia", vo)  # d4_ov
    hE -= e("ja,ia,jb->ib", ov, t1, t1)  # d7_ov
    scalar += e("ia,ia", ov, t1)  # s9
    hhEE -= p("..ab", e("kb,kc,ijba->ijca", ov, t1, t2))  # d11_oovv
    hhhEEE -= p("abb...", p("...aab", e("ia,ijcb,klad->jklbcd", ov, t2, t2)))  # d12_ooovvv
    hhEE -= p("ab..", e("ia,ja,ikcb->jkcb", ov, t1, t2))  # d14_oovv
    hE += e("jb,jiba->ia", ov, t2)  # d15_ov
    hhhEEE -= p("...aba", e("ib,ia,kljbdc->jklcad", ov, t1, t3))  # d17_ooovvv
    hhhEEE -= p("abb...", e("la,ia,lkjdcb->ijkdbc", ov, t1, t3))  # d19_ooovvv
    hhEE += e("kc,kjicba->ijab", ov, t3)  # d20_oovv
    hE -= e("ij,ia->ja", oo, t1)  # d22_ov
    hhEE -= p("ab..", e("jk,jiba->ikab", oo, t2))  # d23_oovv
    hhhEEE -= p("aab...", e("kl,kjicba->ijlabc", oo, t3))  # d24_ooovvv
    hhEE += 1./2 * p("ab..", e("cbad,ia,jd->ijcb", vvvv, t1, t1))  # d27_oovv
    hhhEEE += p("aab...", p("...aba", e("bacd,kd,ijce->ijkbea", vvvv, t1, t2)))  # d29_ooovvv
    hhEE += 1./2 * e("dcba,ijba->ijdc", vvvv, t2)  # d30_oovv
    hhhEEE += 1./2 * p("...abb", e("edcb,jkicba->ijkaed", vvvv, t3))  # d31_ooovvv
    hhEE += p("ab..", e("baci,jc->ijab", vvvo, t1))  # d33_oovv
    hhhEEE += p("aab...", p("...aba", e("dcbk,ijba->ijkdac", vvvo, t2)))  # d34_ooovvv
    hhEE += e("baij->ijba", vvoo)  # d35_oovv
    hhEE -= 1./2 * p("ab..", p("..ab", e("jcad,ia,jb,kd->ikbc", ovvv, t1, t1, t1)))  # d39_oovv
    hE -= e("ibca,ia,jc->jb", ovvv, t1, t1)  # d41_ov
    hhhEEE -= p("aab...", p("...abc", e("ldcb,kc,le,ijba->ijkdae", ovvv, t1, t1, t2)))  # d46_ooovvv
    hhEE += p("..ab", e("iabc,ib,jkcd->jkad", ovvv, t1, t2))  # d48_oovv
    hhhEEE += p("aab...", p("...abc", e("kcdb,ijba,klde->ijlcae", ovvv, t2, t2)))  # d49_ooovvv
    hhEE -= 1./2 * p("..ab", e("kcba,kd,ijba->ijdc", ovvv, t1, t2))  # d51_oovv
    hhhEEE -= 1./2 * p("aab...", p("...aba", e("iacb,jkcb,iled->jklead", ovvv, t2, t2)))  # d52_ooovvv
    hhhEEE -= 1./2 * p("abc...", p("...aab", e("jecd,kc,ld,jiba->iklabe", ovvv, t1, t1, t2)))  # d55_ooovvv
    hhEE -= p("ab..", p("..ab", e("jdcb,kc,jiba->ikad", ovvv, t1, t2)))  # d57_oovv
    hE += 1./2 * e("jcba,jiba->ic", ovvv, t2)  # d58_ov
    hhhEEE += p("...aba", e("ibac,ia,kljced->jkldbe", ovvv, t1, t3))  # d60_ooovvv
    hhhEEE -= 1./2 * p("...abc", e("iacb,ie,kljcbd->jkldea", ovvv, t1, t3))  # d62_ooovvv
    hhhEEE -= p("abb...", p("...abb", e("lead,ia,lkjdcb->ijkebc", ovvv, t1, t3)))  # d64_ooovvv
    hhEE += 1./2 * p("..ab", e("kdcb,kjicba->ijad", ovvv, t3))  # d65_oovv
    hhEE -= p("ab..", p("..ab", e("kbaj,ia,kc->ijcb", ovvo, t1, t1)))  # d68_oovv
    hE += e("jabi,jb->ia", ovvo, t1)  # d70_ov
    hhhEEE -= p("abb...", p("...abc", e("jabi,jd,klbc->ikladc", ovvo, t1, t2)))  # d72_ooovvv
    hhhEEE -= p("abc...", p("...aba", e("kbaj,ia,kldc->ijldbc", ovvo, t1, t2)))  # d74_ooovvv
    hhEE += p("ab..", p("..ab", e("jcbk,jiba->ikac", ovvo, t2)))  # d75_oovv
    hhhEEE += p("abb...", p("...abb", e("jabi,jlkbdc->iklacd", ovvo, t3)))  # d76_ooovvv
    hhEE -= p("..ab", e("kaij,kb->ijba", ovoo, t1))  # d78_oovv
    hhhEEE -= p("aab...", p("...aba", e("kaij,klcb->ijlcab", ovoo, t2)))  # d79_ooovvv
    hhEE += 1./4 * p("ab..", p("..ab", e("kidb,ia,jb,kc,ld->jlac", oovv, t1, t1, t1, t1)))  # d84_oovv
    hE -= e("kjab,ia,jb,kc->ic", oovv, t1, t1, t1)  # d87_ov
    scalar += 1./2 * e("ijab,ia,jb", oovv, t1, t1)  # s93
    hhhEEE += 1./2 * p("abb...", p("...abc", e("ijec,ia,jb,kc,lmed->klmbad", oovv, t1, t1, t1, t2)))  # d97_ooovvv
    hhEE -= p("..ab", e("ilcd,ia,ld,jkcb->jkab", oovv, t1, t1, t2))  # d100_oovv
    hhhEEE -= p("aab...", p("...aba", e("mkbc,kc,ijba,mled->ijlead", oovv, t1, t2, t2)))  # d103_ooovvv
    hhhEEE += p("aab...", p("...abc", e("jicb,ia,klcd,jmbe->klmade", oovv, t1, t2, t2)))  # d105_ooovvv
    hhhEEE += 1./2 * p("abb...", p("...aab", e("ijab,kb,lmac,ijed->klmdec", oovv, t1, t2, t2)))  # d107_ooovvv
    hhEE += 1./2 * p("..ab", e("klbc,ijba,klcd->ijda", oovv, t2, t2))  # d108_oovv
    hhEE += 1./4 * p("..ab", e("klba,lc,kd,ijba->ijdc", oovv, t1, t1, t2))  # d111_oovv
    hhhEEE += 1./2 * p("aab...", p("...aba", e("jicb,ia,klcb,jmed->klmead", oovv, t1, t2, t2)))  # d113_ooovvv
    hhEE += 1./4 * e("klba,ijba,kldc->ijdc", oovv, t2, t2)  # d114_oovv
    hhhEEE += 1./2 * p("abc...", p("...aab", e("kjba,ia,mb,ke,jldc->ilmdce", oovv, t1, t1, t1, t2)))  # d118_ooovvv
    hhEE -= p("ab..", e("ljdc,kc,ld,jiba->ikab", oovv, t1, t1, t2))  # d120_oovv
    hhhEEE -= p("abc...", p("...aab", e("jlcd,kc,jiba,lmde->ikmabe", oovv, t1, t2, t2)))  # d124_ooovvv
    hhEE += 1./2 * p("ab..", e("jldc,jiba,lkdc->ikab", oovv, t2, t2))  # d125_oovv
    hhEE -= p("ab..", p("..ab", e("jlbc,kc,ld,jiba->ikad", oovv, t1, t1, t2)))  # d128_oovv
    hE += e("jkbc,kc,jiba->ia", oovv, t1, t2)  # d130_ov
    hhEE += 1./2 * p("ab..", p("..ab", e("jlbd,jiba,lkdc->ikac", oovv, t2, t2)))  # d131_oovv
    hE += 1./2 * e("kjba,kc,jiba->ic", oovv, t1, t2)  # d133_ov
    hhEE += 1./4 * p("ab..", e("jkab,ia,lb,jkdc->ildc", oovv, t1, t1, t2))  # d136_oovv
    hE += 1./2 * e("ijab,ka,ijbc->kc", oovv, t1, t2)  # d138_ov
    scalar += 1./4 * e("ijba,ijba", oovv, t2)  # s139
    hhhEEE -= p("...aba", e("lmcd,md,le,jkicba->ijkaeb", oovv, t1, t1, t3))  # d142_ooovvv
    hhhEEE -= 1./2 * p("...aba", e("lmdc,lmde,jkicba->ijkaeb", oovv, t2, t3))  # d144_ooovvv
    hhhEEE += 1./4 * p("...abc", e("imdc,ia,me,kljdcb->jklbae", oovv, t1, t1, t3))  # d147_ooovvv
    hhhEEE += 1./4 * p("...abb", e("ijed,ijba,lmkedc->klmcba", oovv, t2, t3))  # d148_ooovvv
    hhhEEE += p("aab...", e("ijba,ma,jb,ilkedc->klmcde", oovv, t1, t1, t3))  # d151_ooovvv
    hhhEEE += 1./2 * p("aab...", e("kmed,mled,kjicba->ijlabc", oovv, t2, t3))  # d153_ooovvv
    hhhEEE -= p("aab...", p("...aab", e("klce,ld,me,kjicba->ijmabd", oovv, t1, t1, t3)))  # d156_ooovvv
    hhEE += e("ijab,jb,ilkadc->klcd", oovv, t1, t3)  # d158_oovv
    hhhEEE += p("aab...", p("...aab", e("ijab,jmbe,ilkadc->klmcde", oovv, t2, t3)))  # d159_ooovvv
    hhEE -= 1./2 * p("..ab", e("klcb,ld,kjicba->ijad", oovv, t1, t3))  # d161_oovv
    hhhEEE -= 1./2 * p("aab...", p("...abb", e("kmcb,mled,kjicba->ijlaed", oovv, t2, t3)))  # d162_ooovvv
    hhhEEE += 1./4 * p("abc...", e("jkab,ia,mb,jkledc->ilmecd", oovv, t1, t1, t3))  # d165_ooovvv
    hhhEEE += 1./4 * p("abb...", e("ijba,lmba,ijkedc->klmced", oovv, t2, t3))  # d166_ooovvv
    hhEE -= 1./2 * p("ab..", e("jkcd,ld,jkicba->ilab", oovv, t1, t3))  # d168_oovv
    hhhEEE -= 1./2 * p("abb...", p("...aab", e("ijab,lmbe,ijkadc->klmcde", oovv, t2, t3)))  # d169_ooovvv
    hE += 1./4 * e("jkcb,jkicba->ia", oovv, t3)  # d170_ov
    hhEE += 1./2 * p("ab..", p("..ab", e("ijcl,ia,jb,kc->klab", oovo, t1, t1, t1)))  # d174_oovv
    hE -= e("kjai,ka,jb->ib", oovo, t1, t1)  # d177_ov
    hhhEEE += 1./2 * p("aab...", p("...abc", e("mlbk,mc,ld,ijba->ijkcad", oovo, t1, t1, t2)))  # d181_ooovvv
    hhhEEE += 1./2 * p("abb...", p("...aab", e("jkai,jkcb,lmad->ilmbcd", oovo, t2, t2)))  # d182_ooovvv
    hhhEEE += p("abc...", p("...abb", e("lkam,ia,ld,kjcb->ijmdbc", oovo, t1, t1, t2)))  # d185_ooovvv
    hhEE += p("ab..", e("jkai,ka,jlcb->ilcb", oovo, t1, t2))  # d187_oovv
    hhhEEE += p("abc...", p("...aba", e("jkai,klab,jmdc->ilmdbc", oovo, t2, t2)))  # d188_ooovvv
    hhEE -= p("ab..", p("..ab", e("jkai,kb,jlac->ilbc", oovo, t1, t2)))  # d190_oovv
    hhEE += 1./2 * p("ab..", e("klaj,ia,klcb->ijcb", oovo, t1, t2))  # d192_oovv
    hE -= 1./2 * e("jkai,jkab->ib", oovo, t2)  # d193_ov
    hhhEEE += p("aab...", e("kmdl,md,kjicba->ijlabc", oovo, t1, t3))  # d195_ooovvv
    hhhEEE -= p("abb...", p("...abb", e("kibj,ia,kmlbdc->jlmacd", oovo, t1, t3)))  # d197_ooovvv
    hhhEEE += 1./2 * p("abc...", e("jkai,la,jkmdcb->ilmcdb", oovo, t1, t3))  # d199_ooovvv
    hhEE -= 1./2 * p("ab..", e("jkai,jklacb->ilcb", oovo, t3))  # d200_oovv
    hhEE += 1./2 * p("..ab", e("ijkl,ia,jb->klab", oooo, t1, t1))  # d203_oovv
    hhhEEE += p("aab...", p("...aba", e("klij,lc,kmba->ijmbca", oooo, t1, t2)))  # d205_ooovvv
    hhEE += 1./2 * e("ijkl,ijba->klba", oooo, t2)  # d206_oovv
    hhhEEE += 1./2 * p("abb...", e("jklm,jkicba->ilmacb", oooo, t3))  # d207_ooovvv
    return hE, hhEE, hhhEEE, scalar
