from util import e, p


def equations_s(oo, ov, vo, vv, oovo, oovv, ovvo, ovvv, t1):
    hE = scalar = 0
    hE += e("ab,ib->ia", vv, t1)  # d1_ov
    hE -= e("ij,ia->ja", oo, t1)  # d3_ov
    hE += e("ai->ia", vo)  # d4_ov
    hE -= e("ib,ia,jb->ja", ov, t1, t1)  # d7_ov
    scalar += e("ia,ia", ov, t1)  # s9
    hE += e("ibac,ia,jc->jb", ovvv, t1, t1)  # d12_ov
    hE += e("ibaj,ia->jb", ovvo, t1)  # d15_ov
    hE -= e("ijab,ia,kb,jc->kc", oovv, t1, t1, t1)  # d19_ov
    scalar += 1./2 * e("jiba,ia,jb", oovv, t1, t1)  # s24
    hE += e("jiak,ia,jb->kb", oovo, t1, t1)  # d27_ov
    return hE, scalar


def equations_sd(oo, ov, vo, vv, oooo, oovo, oovv, ovoo, ovvo, ovvv, vvoo, vvvo, vvvv, t1, t2):
    hE = hhEE = scalar = 0
    hE += e("ab,ib->ia", vv, t1)  # d1_ov
    hhEE += p("..ab", e("ab,ijbc->ijac", vv, t2))  # d2_oovv
    hE -= e("ji,ja->ia", oo, t1)  # d4_ov
    hhEE -= p("ab..", e("ji,jkba->ikba", oo, t2))  # d5_oovv
    hE += e("ai->ia", vo)  # d6_ov
    hE -= e("ja,ia,jb->ib", ov, t1, t1)  # d9_ov
    hhEE -= p("ab..", e("ia,ja,ikcb->jkcb", ov, t1, t2))  # d10_oovv
    hhEE -= p("..ab", e("ia,ic,jkab->jkcb", ov, t1, t2))  # d12_oovv
    scalar += e("ia,ia", ov, t1)  # s13
    hE += e("jb,jiba->ia", ov, t2)  # d16_ov
    hhEE += 1./2 * p("ab..", e("dcab,ia,jb->ijdc", vvvv, t1, t1))  # d19_oovv
    hhEE += 1./2 * e("dcba,ijba->ijdc", vvvv, t2)  # d20_oovv
    hhEE += p("ab..", e("baci,jc->ijab", vvvo, t1))  # d22_oovv
    hhEE += e("baij->ijba", vvoo)  # d23_oovv
    hhEE -= 1./2 * p("ab..", p("..ab", e("iacb,id,jc,kb->jkda", ovvv, t1, t1, t1)))  # d27_oovv
    hE -= e("jbac,ia,jc->ib", ovvv, t1, t1)  # d29_ov
    hhEE += p("ab..", p("..ab", e("jbca,ia,jkcd->ikbd", ovvv, t1, t2)))  # d30_oovv
    hhEE -= 1./2 * p("..ab", e("kcba,kd,ijba->ijdc", ovvv, t1, t2))  # d32_oovv
    hhEE += p("..ab", e("iacb,ic,jkbd->jkad", ovvv, t1, t2))  # d34_oovv
    hE += 1./2 * e("iacb,ijcb->ja", ovvv, t2)  # d38_ov
    hhEE -= p("ab..", p("..ab", e("jcak,ia,jb->ikbc", ovvo, t1, t1)))  # d41_oovv
    hE += e("jabi,jb->ia", ovvo, t1)  # d43_ov
    hhEE += p("ab..", p("..ab", e("jcbk,jiba->ikac", ovvo, t2)))  # d44_oovv
    hhEE -= p("..ab", e("ibjk,ia->jkab", ovoo, t1))  # d46_oovv
    hhEE += 1./4 * p("ab..", p("..ab", e("licb,ia,jb,kc,ld->jkad", oovv, t1, t1, t1, t1)))  # d51_oovv
    hhEE += 1./4 * p("ab..", e("ijdc,kc,ld,ijba->klab", oovv, t1, t1, t2))  # d52_oovv
    hE += e("ijba,ia,jc,kb->kc", oovv, t1, t1, t1)  # d55_ov
    hhEE -= p("ab..", p("..ab", e("lidb,ia,jb,lkdc->jkac", oovv, t1, t1, t2)))  # d56_oovv
    hhEE -= p("ab..", e("ljab,ia,jb,lkdc->ikdc", oovv, t1, t1, t2))  # d58_oovv
    hE += 1./2 * e("jkac,ia,jkcb->ib", oovv, t1, t2)  # d62_ov
    hhEE += 1./4 * p("..ab", e("jicb,ia,jd,klcb->klda", oovv, t1, t1, t2))  # d65_oovv
    hhEE += p("..ab", e("jiab,ia,jc,klbd->klcd", oovv, t1, t1, t2))  # d67_oovv
    hE += 1./2 * e("kjba,kc,jiba->ic", oovv, t1, t2)  # d71_ov
    scalar += 1./2 * e("jiba,ia,jb", oovv, t1, t1)  # s73
    hE += e("ijab,ia,jkbc->kc", oovv, t1, t2)  # d76_ov
    hhEE += 1./2 * p("..ab", e("ijab,ijbc,klad->klcd", oovv, t2, t2))  # d78_oovv
    hhEE += 1./4 * e("ijdc,ijba,kldc->klba", oovv, t2, t2)  # d80_oovv
    hhEE += 1./2 * p("ab..", e("ljba,jiba,lkdc->ikdc", oovv, t2, t2))  # d82_oovv
    hhEE += 1./2 * p("ab..", p("..ab", e("ijab,jkbc,ilad->klcd", oovv, t2, t2)))  # d84_oovv
    scalar += 1./4 * e("ijba,ijba", oovv, t2)  # s88
    hhEE += 1./2 * p("ab..", p("..ab", e("kjai,jb,kc,la->ilbc", oovo, t1, t1, t1)))  # d92_oovv
    hhEE += 1./2 * p("ab..", e("jkal,ia,jkcb->ilcb", oovo, t1, t2))  # d93_oovv
    hE -= e("jkai,ja,kb->ib", oovo, t1, t1)  # d96_ov
    hhEE -= p("ab..", p("..ab", e("jkai,kc,jlab->ilcb", oovo, t1, t2)))  # d97_oovv
    hhEE -= p("ab..", e("ikaj,ia,klcb->jlcb", oovo, t1, t2))  # d99_oovv
    hE -= 1./2 * e("ijbk,ijba->ka", oovo, t2)  # d103_ov
    hhEE += 1./2 * p("..ab", e("jikl,ia,jb->klba", oooo, t1, t1))  # d106_oovv
    hhEE += 1./2 * e("ijkl,ijba->klba", oooo, t2)  # d107_oovv
    return hE, hhEE, scalar


def equations_sdt(oo, ov, vo, vv, oooo, oovo, oovv, ovoo, ovvo, ovvv, vvoo, vvvo, vvvv, t1, t2, t3):
    hE = hhEE = hhhEEE = scalar = 0
    hE += e("ab,ib->ia", vv, t1)  # d1_ov
    hhEE += p("..ab", e("ab,ijbc->ijac", vv, t2))  # d2_oovv
    hhhEEE += p("...aba", e("ab,jkibdc->ijkcad", vv, t3))  # d3_ooovvv
    hE -= e("ji,ja->ia", oo, t1)  # d5_ov
    hhEE -= p("ab..", e("ji,jkba->ikba", oo, t2))  # d6_oovv
    hhhEEE -= p("abb...", e("ji,jlkcba->iklcab", oo, t3))  # d7_ooovvv
    hE += e("ai->ia", vo)  # d8_ov
    hE -= e("ja,ia,jb->ib", ov, t1, t1)  # d11_ov
    hhEE -= p("ab..", e("ia,ka,ijcb->jkbc", ov, t1, t2))  # d12_oovv
    hhhEEE -= p("abb...", e("ia,ja,ilkdcb->jkldbc", ov, t1, t3))  # d13_ooovvv
    hhEE -= p("..ab", e("kb,kc,ijba->ijca", ov, t1, t2))  # d15_oovv
    hhhEEE -= p("...aba", e("ib,ia,kljbdc->jklcad", ov, t1, t3))  # d16_ooovvv
    scalar += e("ia,ia", ov, t1)  # s17
    hhhEEE -= p("abb...", p("...aab", e("jd,jiba,kldc->iklabc", ov, t2, t2)))  # d19_ooovvv
    hE += e("jb,jiba->ia", ov, t2)  # d21_ov
    hhEE += e("kc,kjicba->ijab", ov, t3)  # d24_oovv
    hhEE += 1./2 * p("ab..", e("bacd,ic,jd->ijba", vvvv, t1, t1))  # d27_oovv
    hhhEEE += p("abb...", p("...aab", e("edca,ia,jkcb->ijkdeb", vvvv, t1, t2)))  # d28_ooovvv
    hhEE += 1./2 * e("dcba,ijba->ijdc", vvvv, t2)  # d30_oovv
    hhhEEE += 1./2 * p("...abb", e("badc,jkidce->ijkeba", vvvv, t3))  # d31_ooovvv
    hhEE += p("ab..", e("baci,jc->ijab", vvvo, t1))  # d33_oovv
    hhhEEE += p("abb...", p("...aab", e("baci,jkcd->ijkabd", vvvo, t2)))  # d34_ooovvv
    hhEE += e("baij->ijba", vvoo)  # d35_oovv
    hhEE -= 1./2 * p("ab..", p("..ab", e("jbac,ia,jd,kc->ikdb", ovvv, t1, t1, t1)))  # d39_oovv
    hhhEEE -= 1./2 * p("abc...", p("...aab", e("kdae,ia,le,kjcb->ijlcbd", ovvv, t1, t1, t2)))  # d40_ooovvv
    hhhEEE -= p("abb...", p("...abc", e("jbca,ia,je,klcd->iklbed", ovvv, t1, t1, t2)))  # d42_ooovvv
    hE -= e("iabc,jb,ic->ja", ovvv, t1, t1)  # d43_ov
    hhEE += p("ab..", p("..ab", e("iacb,kb,ijcd->jkda", ovvv, t1, t2)))  # d46_oovv
    hhhEEE += p("aab...", p("...aab", e("iabc,lc,ikjbed->jkldea", ovvv, t1, t3)))  # d47_ooovvv
    hhEE -= 1./2 * p("..ab", e("kdba,kc,ijba->ijcd", ovvv, t1, t2))  # d50_oovv
    hhhEEE -= 1./2 * p("...abc", e("iacb,id,kljcbe->jkleda", ovvv, t1, t3))  # d51_ooovvv
    hhEE -= p("..ab", e("kcbd,kd,ijba->ijca", ovvv, t1, t2))  # d53_oovv
    hhhEEE += p("...aba", e("iabc,ib,kljced->jkldae", ovvv, t1, t3))  # d54_ooovvv
    hhhEEE -= p("abb...", p("...abc", e("jcdb,jiba,klde->iklace", ovvv, t2, t2)))  # d56_ooovvv
    hhhEEE -= 1./2 * p("abb...", p("...aab", e("jced,jiba,kled->iklabc", ovvv, t2, t2)))  # d58_ooovvv
    hE += 1./2 * e("iacb,ijcb->ja", ovvv, t2)  # d61_ov
    hhEE += 1./2 * p("..ab", e("iacb,ikjcbd->jkda", ovvv, t3))  # d65_oovv
    hhEE -= p("ab..", p("..ab", e("jabi,kb,jc->ikac", ovvo, t1, t1)))  # d68_oovv
    hhhEEE -= p("abc...", p("...aba", e("kbaj,ia,kldc->ijldbc", ovvo, t1, t2)))  # d69_ooovvv
    hhhEEE -= p("aab...", p("...abc", e("kdbl,kc,ijba->ijlcad", ovvo, t1, t2)))  # d71_ooovvv
    hE += e("ibaj,ia->jb", ovvo, t1)  # d72_ov
    hhEE += p("ab..", p("..ab", e("jabi,jkbc->ikac", ovvo, t2)))  # d75_oovv
    hhhEEE += p("abb...", p("...abb", e("jabi,jlkbdc->iklacd", ovvo, t3)))  # d76_ooovvv
    hhEE -= p("..ab", e("kaij,kb->ijba", ovoo, t1))  # d78_oovv
    hhhEEE -= p("aab...", p("...aba", e("kaij,klcb->ijlcab", ovoo, t2)))  # d79_ooovvv
    hhEE += 1./4 * p("ab..", p("..ab", e("kjac,ia,jb,kd,lc->ildb", oovv, t1, t1, t1, t1)))  # d84_oovv
    hhhEEE += 1./2 * p("abc...", p("...aab", e("ijba,je,lb,ma,ikdc->klmcde", oovv, t1, t1, t1, t2)))  # d85_ooovvv
    hhEE += 1./4 * p("ab..", e("jkda,ia,ld,jkcb->ilbc", oovv, t1, t1, t2))  # d87_oovv
    hhhEEE += 1./4 * p("abc...", e("jked,ld,me,jkicba->ilmabc", oovv, t1, t1, t3))  # d88_ooovvv
    hhhEEE += 1./2 * p("aab...", p("...abc", e("klbd,kc,le,md,ijba->ijmcae", oovv, t1, t1, t1, t2)))  # d91_ooovvv
    hE += e("jiab,ia,kb,jc->kc", oovv, t1, t1, t1)  # d92_ov
    hhEE += p("ab..", p("..ab", e("lkca,ia,ld,kjcb->ijdb", oovv, t1, t1, t2)))  # d95_oovv
    hhhEEE += p("aab...", p("...aab", e("mkcd,ld,me,kjicba->ijlabe", oovv, t1, t1, t3)))  # d96_ooovvv
    hhEE -= p("ab..", e("jkba,ia,jb,kldc->ildc", oovv, t1, t1, t2))  # d98_oovv
    hhhEEE -= p("abb...", e("ikab,ia,jb,kmledc->jlmecd", oovv, t1, t1, t3))  # d99_ooovvv
    hhhEEE += 1./2 * p("abb...", p("...aab", e("ijba,ka,ijdc,lmbe->klmcde", oovv, t1, t2, t2)))  # d101_ooovvv
    hhhEEE += p("abc...", p("...abb", e("kjbc,lc,jiba,kmed->ilmaed", oovv, t1, t2, t2)))  # d103_ooovvv
    hE -= 1./2 * e("ijbc,kc,ijba->ka", oovv, t1, t2)  # d106_ov
    hhEE -= 1./2 * p("ab..", e("jkcd,ld,jkicba->ilab", oovv, t1, t3))  # d110_oovv
    hhEE += 1./4 * p("..ab", e("ijcb,ia,jd,klcb->klad", oovv, t1, t1, t2))  # d114_oovv
    hhhEEE += 1./4 * p("...abc", e("imdc,ia,me,kljdcb->jklbae", oovv, t1, t1, t3))  # d115_ooovvv
    hhEE -= p("..ab", e("jiab,ic,ja,klbd->klcd", oovv, t1, t1, t2))  # d117_oovv
    hhhEEE += p("...aba", e("ijba,ia,jc,lmkbed->klmdce", oovv, t1, t1, t3))  # d118_ooovvv
    hhhEEE -= p("abb...", p("...abc", e("kicd,ia,kjcb,lmde->jlmbae", oovv, t1, t2, t2)))  # d120_ooovvv
    hhhEEE += 1./2 * p("abb...", p("...aab", e("jkdc,ke,jiba,lmdc->ilmabe", oovv, t1, t2, t2)))  # d122_ooovvv
    hE -= 1./2 * e("kicb,ia,kjcb->ja", oovv, t1, t2)  # d125_ov
    hhEE -= 1./2 * p("..ab", e("lidc,ia,lkjdcb->jkba", oovv, t1, t3))  # d129_oovv
    scalar += 1./2 * e("ijab,ia,jb", oovv, t1, t1)  # s131
    hhhEEE -= p("aab...", p("...aba", e("lica,ia,jkcb,lmed->jkmebd", oovv, t1, t2, t2)))  # d133_ooovvv
    hE += e("jiba,ia,jkbc->kc", oovv, t1, t2)  # d135_ov
    hhEE += e("klcd,ld,kjicba->ijab", oovv, t1, t3)  # d138_oovv
    hhEE += 1./2 * p("..ab", e("ijdb,ijba,kldc->klac", oovv, t2, t2))  # d143_oovv
    hhhEEE += 1./2 * p("aab...", p("...aba", e("lmbe,ijba,lmkedc->ijkdac", oovv, t2, t3)))  # d144_ooovvv
    hhEE += 1./4 * e("klba,ijba,kldc->ijdc", oovv, t2, t2)  # d147_oovv
    hhhEEE += 1./4 * p("aab...", e("lmba,ijba,lmkedc->ijkedc", oovv, t2, t3))  # d148_ooovvv
    hhEE -= 1./2 * p("ab..", e("jkba,jiba,kldc->ildc", oovv, t2, t2))  # d151_oovv
    hhhEEE += 1./2 * p("abb...", p("...aba", e("jkdc,jiba,kmldce->ilmaeb", oovv, t2, t3)))  # d152_ooovvv
    hhEE += 1./2 * p("ab..", p("..ab", e("jkbc,jiba,klcd->ilad", oovv, t2, t2)))  # d154_oovv
    hhhEEE += p("abb...", p("...abb", e("jmbe,jiba,mlkedc->iklacd", oovv, t2, t3)))  # d155_ooovvv
    hhhEEE -= 1./2 * p("abb...", e("jkba,jiba,kmledc->ilmecd", oovv, t2, t3))  # d157_ooovvv
    hhhEEE += 1./4 * p("...abb", e("ijba,ijdc,lmkbae->klmedc", oovv, t2, t3))  # d159_ooovvv
    hhhEEE -= 1./2 * p("...aba", e("ijab,ijac,lmkbed->klmdce", oovv, t2, t3))  # d161_ooovvv
    scalar += 1./4 * e("ijba,ijba", oovv, t2)  # s162
    hE += 1./4 * e("jkcb,jkicba->ia", oovv, t3)  # d170_ov
    hhEE += 1./2 * p("ab..", p("..ab", e("kjai,jb,la,kc->ilbc", oovo, t1, t1, t1)))  # d174_oovv
    hhhEEE += p("abc...", p("...aab", e("libm,ia,jb,lkdc->jkmdca", oovo, t1, t1, t2)))  # d175_ooovvv
    hhEE += 1./2 * p("ab..", e("jkal,ia,jkcb->ilcb", oovo, t1, t2))  # d177_oovv
    hhhEEE += 1./2 * p("abc...", e("jkai,la,jkmdcb->ilmcdb", oovo, t1, t3))  # d178_ooovvv
    hhhEEE += 1./2 * p("abb...", p("...abc", e("jkai,kc,jd,lmab->ilmcdb", oovo, t1, t1, t2)))  # d181_ooovvv
    hE -= e("ijak,ia,jb->kb", oovo, t1, t1)  # d182_ov
    hhEE -= p("ab..", p("..ab", e("jkbl,kc,jiba->ilac", oovo, t1, t2)))  # d185_oovv
    hhhEEE -= p("abb...", p("...abb", e("kibj,ia,kmlbdc->jlmacd", oovo, t1, t3)))  # d186_ooovvv
    hhEE -= p("ab..", e("ikal,ia,kjcb->jlbc", oovo, t1, t2))  # d188_oovv
    hhhEEE += p("aab...", e("kldm,ld,kjicba->ijmabc", oovo, t1, t3))  # d189_ooovvv
    hhhEEE += 1./2 * p("aab...", p("...aba", e("ijdm,ijba,kldc->klmbca", oovo, t2, t2)))  # d191_ooovvv
    hhhEEE += p("abc...", p("...aab", e("jlck,jiba,lmcd->ikmabd", oovo, t2, t2)))  # d193_ooovvv
    hE -= 1./2 * e("ijbk,ijba->ka", oovo, t2)  # d196_ov
    hhEE -= 1./2 * p("ab..", e("jkcl,jkicba->ilab", oovo, t3))  # d200_oovv
    hhEE += 1./2 * p("..ab", e("ijkl,ia,jb->klab", oooo, t1, t1))  # d203_oovv
    hhhEEE += p("abb...", p("...aba", e("iklm,ia,kjcb->jlmbac", oooo, t1, t2)))  # d204_ooovvv
    hhEE += 1./2 * e("klij,klba->ijba", oooo, t2)  # d206_oovv
    hhhEEE += 1./2 * p("abb...", e("jklm,jkicba->ilmacb", oooo, t3))  # d207_ooovvv
    return hE, hhEE, hhhEEE, scalar
